//! Instances of zones.
//!
//! An _instance_ is a snapshot of the contents of a zone (the specific records
//! within it). Cascade maintains information about various instances, e.g. how
//! they were generated and information needed to re-sign them.
//!
//! Instances can be classified by their origin and purpose: _loaded_ instances
//! are generated by Cascade's zone loader (by loading from a configured zone
//! source) and _signed_ instances are generated by the zone signer (by signing
//! a loaded instance or re-signing a prior signed instance). An "instance" in
//! general refers to a pair of loaded and signed instances (where the signed
//! instance was generated from the loaded instance).
//!
//! Instances (whether loaded or signed) can be in one of four states:
//!
//! - _Upcoming_ (i.e. _Next_): The instance is being generated and reviewed. If
//!   all goes well, it will become _Current_.
//!
//! - _Current_ (i.e. _Published_): The instance has been accepted and is now
//!   being published by Cascade as the latest authoritative version.
//!
//! - _Obsolete_: The instance was previously _Current_, but has since been
//!   replaced by a new _Current_ instance.
//!
//! - _Abandoned_: The instance failed to be accepted (e.g. due to an error in
//!   generation or being rejected at review).
//!
//! Instances are tracked by [`Instances`]. At any time, there are (at most)
//! one loaded+signed pair of upcoming instances, and one loaded+signed pair
//! of current instances. There may be any number of obsolete and abandoned
//! instances.

use domain::new::base::Serial;

//----------- Instances --------------------------------------------------------

/// State regarding instances of the zone.
///
/// See [the module-level documentatino](self) for more information.
#[derive(Debug, Default)]
pub struct Instances {
    /// The upcoming instance, if any.
    ///
    /// This is [`Some`] when a new instance is being built (a new instance of
    /// the zone is being loaded, or the zone is being re-signed).
    pub upcoming: Option<UpcomingInstance>,

    /// The current/published instance.
    ///
    /// In general, this will be [`Some`]; most zones have a current instance.
    /// It is [`None`] if an instance of the zone has never been accepted, or
    /// the instance could not be restored from disk on startup.
    pub current: Option<CurrentInstance>,
    //
    // TODO:
    // - The next usable loaded/signed instance IDs.
    //   These increase monotonically, even if instances are abandoned.
    // - Obsolete instances.
    // - Abandoned instances.
}

//----------- CurrentInstance --------------------------------------------------

/// The current/published instance of a zone.
///
/// This type holds information about the current (loaded and signed) instance
/// of a zone, which is published by Cascade.
#[derive(Debug)]
pub struct CurrentInstance {
    /// The current loaded instance.
    ///
    /// This describes the instance loaded from the zone source.
    pub loaded: LoadedInstance,

    /// The current signed instance.
    ///
    /// This describes the signed instance generated by Cascade.
    pub signed: SignedInstance,
    //
    // TODO:
    // - When the instance was published.
}

//----------- UpcomingInstance -------------------------------------------------

/// An upcoming instance of a zone.
///
/// This type holds information about an upcoming (loaded and signed) instance
/// of a zone, which is being generated by Cascade to replace the current one.
/// In case of a re-sign operation, only the signed instance is being replaced.
///
/// There are two reasons an upcoming instance may exist:
///
/// - A new instance of the zone is being loaded. The current instance can be
///   in any state. An upcoming loaded instance will exist, and an upcoming
///   signed instance might exist (if signing is enabled).
///
/// - The current instance of the zone is being re-signed. A current loaded
///   instance exists, but a current signed instance might not (e.g. if signing
///   was disabled and has now been enabled). An upcoming loaded instance will
///   not exist, but an upcoming signed instance will exist.
#[derive(Debug)]
pub struct UpcomingInstance {
    /// The upcoming loaded instance, if any.
    ///
    /// This describes the instance loaded from the zone source. It is [`Some`]
    /// if/when loading is complete; if a re-sign operation is happening, it is
    /// only [`None`].
    pub loaded: Option<LoadedInstance>,

    /// The upcoming signed instance, if any.
    ///
    /// This describes the signed instance generated by Cascade. It is [`Some`]
    /// if/when signing is complete.
    pub signed: Option<SignedInstance>,
    //
    // TODO:
    // - When the instance was initiated.
    // - The cause of initiation (e.g. reception of DNS NOTIFY).
    // - The policy used for generating the instance.
    //   (with such a field, policy changes during generation can be ignored.)
}

//----------- LoadedInstance ---------------------------------------------------

/// A loaded instance of a zone.
#[derive(Debug)]
pub struct LoadedInstance {
    /// The SOA serial of this instance.
    pub serial: Serial,
    //
    // TODO:
    // - Instance ID.
    // - How the instance was loaded (time, source, duration, size).
    // - Whether the zone contains DNSSEC records (for pass-through mode).
    // - Basic details of the zone:
    //   - How many records it contains (especially NS, DS, glue records).
    //   - Total memory usage.
}

//----------- SignedInstance ---------------------------------------------------

/// A signed instance of a zone.
#[derive(Debug)]
pub struct SignedInstance {
    /// The SOA serial of this instance.
    pub serial: Serial,
    //
    // TODO:
    // - Instance ID.
    // - How the instance was signed:
    //   - time, source, duration, size
    //   - Whether re-signing occurred, and what was re-signed.
    // - Basic details of the signed zone:
    //   - How many records it contains (especially RRSIG, NSEC/NSEC3 records).
    //   - How many records from the loaded instance are included.
    //   - Total memory usage (excluding the loaded instance).
    // - DNSSEC details:
    //   - NSEC or NSEC3 records (incl. rollovers).
    //   - ZONEMD (incl. algorithms and rollovers).
    //   - Zone signing keys (incl. rollovers).
    //   - The earliest signature expiration time.
    //   - Extensions/overrides used during signing
    //     - See 'apex_{remove,extra}'.
}
